### ISSUE TITLE
decodeBase64 not work

### ISSUE THREAD

**Issue by runfan** [andris9/mimelib#29]
this is the attachment name. but can not decode
=??B?PT9VVEYtOD9RPz1FNT05Mz1BOD1FNT1BRD05MD01Rj1FOT04Mj1BRT1FNz1BRT1CMT0=?==??B?NUZJT1M9NUY9RTY9QjU9OEI9RTg9QUY9OTU9RTc9OTQ9QTg9RTQ9QkU9OEIyMDE1MTI=?==??B?MjIueGxzeD89?=

**Comment by andris9** [comment]
This mime encoded-word is invalid. RFC2047 #2 requires charset value to exist (at least one char). In your example it is missing. It should start with *=?some-charset?B...* and not *=??B...*

Is this a real word example, where did you get it from?

**Comment by runfan** [comment]
thanks , i think there is something wrong in this mail.
