### ISSUE TITLE
parseAddresses with comma (",") in name

### ISSUE THREAD

**Issue by databank** [andris9/mimelib#30]
Hi Andris, 

First thank you for all your great work!

The following issue I'm OFTEN getting into looks like this:
require("mimelib").parseAddresses("Company, Inc. <mb@domain.tld>")
returns [ ] with
0: Object {address: "", name: "Company"}
1: Object {address: "mb@domain.tld", name: "Inc."}

I know name should be wrapped into "" but can't expect all email senders to behave
so my question:
Is there anything mimelib could do about it ?

Thanks,
Adrian

**Comment by andris9** [comment]
This behavior is similar to other mail clients, for example both Gmail webmail and OSX Mail app split the address into two where the first address is `"Company <>"` and second one is `"Inc. <mb@domain.tld>"`

This is how OSX Mail app displays such e-mail address:

![](https://cldup.com/SuEw3j6sSU.png)

Anyway, such address formatting is non-standard and there's not much to do about it. Blindly joining different parts into single address might cause even more problems.
