### ISSUE TITLE
decodeMimeWord does not work

### ISSUE THREAD

**Issue by pranshu792** [andris9/mimelib#35]
@andris9 While decoding a mime line using decodeMimeWord does not work, `=?Windows-1252?Q?Pr=E9sentation?= Pack Famille - Avantage =?Windows-1252?Q?30=80?= =?Windows-1252?Q?rembours=E9s?=`

Can you please have a look ?

**Comment by andris9** [comment]
use `decodeMimeWords`

**Comment by pranshu792** [comment]
Thanks, it works by `mimelib.mimeFunctions.decodeMimeWords`. I think docs needs to be updated.
