### ISSUE TITLE
And the license is...?

### ISSUE THREAD

**Issue by jan-kiszka** [andris9/mimelib#36]
README.md states "mimelib license is" and then it ends. And LICENSE also has an empty conditions sections. Please clarify if what is reported by npm - MIT - is also what should go there. Do you need a PR to adjust both files then? TIA!

**Comment by andris9** [comment]
This module is deprecated

**Comment by jan-kiszka** [comment]
Can you clarify it nevertheless? I've a dependency chain here that is still using it (node-red-node-email 0.1.23 -> mailparser ^0.6.1 -> mimelib).

**Comment by andris9** [comment]
Ok. I've been using EUPL-v1.1 for all my newer projects, so I set the same license for this module as well, now all automatic detectors should properly pick up the license for this module.

**Comment by jan-kiszka** [comment]
Thanks. Should be fine for the existing use case.

Just one note, not only in this context: changing the license may require the acknowledgement of all copyright holders of affected code. Be careful when doing this in your projects.

**Comment by andris9** [comment]
Yeah, this is not an issue. All my projects are 99% written by myself, all other contributions are not significant and can be easily removed if the actual author of that specific line is not fine with the change.
